# Generated by Django 4.1.7 on 2023-02-26 15:08

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('subject_number', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname_name', models.CharField(max_length=100, verbose_name='Фамилия Имя')),
                ('group_number', models.IntegerField(verbose_name='Номер группы')),
                ('number_of_questions', models.IntegerField(verbose_name='Количество вопросов')),
                ('number_of_answered_questions', models.IntegerField(default=0, verbose_name='Количестов отвеченных вопросов')),
                ('questions', models.JSONField(verbose_name='Вопросы теста')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsType4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('right_answer', models.DecimalField(decimal_places=5, max_digits=5, verbose_name="Числовой ответ (разделитель ' , ')")),
                ('Тема вопроса', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name': 'Вопрос 4 типа',
                'verbose_name_plural': 'Вопросы 4 типа',
            },
        ),
        migrations.CreateModel(
            name='QuestionsType3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(upload_to='main/static/main/uploaded_img', verbose_name='Изображение для вопроса')),
                ('answer_options', django_jsonform.models.fields.JSONField(verbose_name='Варианты ответов')),
                ('right_answer', models.IntegerField(verbose_name='Номер верного ответа (по порядку)')),
                ('Тема вопроса', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name': 'Вопрос 3 типа',
                'verbose_name_plural': 'Вопросы 3 типа',
            },
        ),
        migrations.CreateModel(
            name='QuestionsType2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer_options', django_jsonform.models.fields.JSONField(verbose_name='Варианты ответов')),
                ('right_answer', models.IntegerField(verbose_name='Номер верного ответа (по порядку)')),
                ('Тема вопроса', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name': 'Вопрос 2 типа',
                'verbose_name_plural': 'Вопросы 2 типа',
            },
        ),
        migrations.CreateModel(
            name='QuestionsType1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer_options', django_jsonform.models.fields.JSONField(verbose_name='Варианты ответов')),
                ('right_answer', models.IntegerField(verbose_name='Номер верного ответа (по порядку)')),
                ('Тема вопроса', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name': 'Вопрос 1 типа',
                'verbose_name_plural': 'Вопросы 1 типа',
            },
        ),
    ]
