# Generated by Django 4.1.7 on 2023-02-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstype1model',
            name='Тема вопроса',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='questionstype2model',
            name='Тема вопроса',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='questionstype3model',
            name='Тема вопроса',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='questionstype4model',
            name='Тема вопроса',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
    ]
