# Generated by Django 4.1.7 on 2023-02-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questionstype1model_тема вопроса_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionstype1model',
            old_name='Тема вопроса',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='questionstype2model',
            old_name='Тема вопроса',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='questionstype3model',
            old_name='Тема вопроса',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='questionstype4model',
            old_name='Тема вопроса',
            new_name='subject',
        ),
    ]
