# Generated by Django 4.1.7 on 2023-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testmodel_number_of_correctly_answered_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='testmodel',
            name='number_of_incorrectly_answered_questions',
            field=models.IntegerField(default=0, verbose_name='Количестов неправильно отвеченных вопросов'),
        ),
    ]
