# Generated by Django 4.1.7 on 2023-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_questionstype2model_answer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
    ]
